---
- name: "{{ dc_name }} | TLS cert and key check"
  stat:
    path: "{{ dnp_nginx_certs_dir }}/{{ proxy_virtual_host }}.{{ item }}"
    get_checksum: false
    get_md5: false
  register: service_tls_and_key
  with_items: [crt, key]

- name: "{{ dc_name }} | TLS cert and key"
  copy:
    src: "{{ dc_src_certs_dir }}/{{ proxy_virtual_host }}.{{ item.item }}"
    dest: "{{ dnp_nginx_certs_dir }}/"
    owner: root
    group: ssl-cert
    mode: 0640
  sudo: True
  when: not item.stat.exists
  with_items: service_tls_and_key.results
